#!/bin/bash

# Go to script's location
cd $(dirname $0)

if [ $# -ge 1 ]
then
	repo="$1"
else
	repo="repo/"
fi

../util/printtitle "NORMINETTE"
../util/normcheck $repo

../util/printtitle "COMPILE"
make -C $repo -s all clean
gcc tests/test.c $repo/libftprintf.a -o ft_printf
gcc tests/test_printf.c -o printf

../util/printtitle "TESTS"
./ft_printf > ft_printf.out
./printf > printf.out
../util/testdiff ft_printf.out printf.out

rm -f ft_printf printf
make -C $repo -s fclean

../util/printtitle "BONUS COMPILE"
make -C $repo -s bonus clean
gcc tests/test_bonus.c $repo/libftprintf.a -o ft_printf
gcc tests/test_printf_bonus.c -o printf

../util/printtitle "BONUS TESTS"
./ft_printf > ft_printf_bonus.out
./printf > printf_bonus.out
../util/testdiff ft_printf_bonus.out printf_bonus.out

rm -f ft_printf printf
make -C $repo -s fclean