#!/bin/bash

COLOR_GREEN="\033[0;32m"
COLOR_NONE="\033[0m"
COLOR_RED="\033[0;31m"

result=0

echo "----   NORMINETTE   ----"

norm=$(norminette libft/ | grep -v ': OK!$')
if [ $(echo "$norm" | wc -w) -eq 0 ]
then
	echo -e "${COLOR_GREEN}No norm errors!${COLOR_NONE}"
else
	echo -e "${COLOR_RED}$norm${COLOR_NONE}"
	result=1
fi

echo "----   COMPILE   ----"

make -s -C tests/ all clean
if [ $? -eq 0 ]
then
	echo -e "${COLOR_GREEN}Compilation successful!${COLOR_NONE}"
else
	echo -e "${COLOR_RED}Compilation failed...${COLOR_NONE}"
	result=1
	exit $result
fi

echo "----   TESTS   ----"

valgrind --xml-fd=10 --show-leak-kinds=all --xml=yes tests/tester 10>valgrind.out
if [ $? -ne 0 ]
then
	result=1
fi

make -s -C tests/ fclean

exit $result