#!/bin/bash

make -s -C tests/ all clean


tests/tester "01" "0" "1" "101011" "-111" "   +1011" "++1" "55" "10151" "10 01 10 01" > binary.out
diff tests/binary.txt binary.out > /dev/null
if [ $? -ne 0 ]
then
	echo "Binary test KO"
else
	echo "Binary test OK"
fi

tests/tester "0123456789" "0" "5" "+0" "-0" "+5" "-5" "     500" "-432" "  -6" "+-7" "kkk" "1k23j" "2147483647" "2147483648" "-2147483648" "-2147483647" "-2147483649" > decimal.out
diff tests/decimal.txt decimal.out > /dev/null
if [ $? -ne 0 ]
then
	echo "Decimal test KO"
else
	echo "Decimal test OK"
fi

make -s -C tests/ fclean
rm -f binary.out decimal.out