#!/bin/bash

red="\033[0;31m"
green="\033[0;32m"
nocolor="\033[0m"

d=$(diff $1 $2)
if [ $? -ne 0 ]
then
	if [ $? -eq 1 ]
	then
		echo -e "${red}Test KO${nocolor}, diff below"
		echo "$d"
	else
		echo -e "${red}Test KO${nocolor}"
	fi
else
	echo -e "${green}Test OK${nocolor}"
fi