#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Must pass list of arguments"
	exit 1
fi

make -s -C repo/ all clean
../util/compilecheck $?
if [ $? -ne 0 ]
then
	exit 1
fi

RESULT1="$(repo/push_swap "$1"; echo x)"
RESULT2="${RESULT1%x}"
echo -n "$RESULT2"
echo -n "$RESULT2" | wc -l | tr -d ' '
echo -n "$RESULT2" | ./checker_Mac $1

make -s -C repo/ fclean