#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Must pass list of arguments"
	exit 1
fi

make -s -C repo/ all bonus clean
../util/compilecheck $?
if [ $? -ne 0 ]
then
	exit 1
fi

make -s -C gen/ all clean
../util/compilecheck $?
if [ $? -ne 0 ]
then
	exit 1
fi

RESULT1="$(repo/push_swap "$(gen/generator $1)"; echo x)"
RESULT2="${RESULT1%x}"
echo -n "$RESULT2" | wc -l | tr -d ' '
echo -n "$RESULT2" | repo/checker $1

make -s -C repo/ fclean
make -s -C gen/ fclean