#!/bin/bash

# Go to script's location
cd $(dirname $0)

if [ $# -ge 1 ]
then
	repo="$1"
else
	repo="repo/"
fi

../util/printtitle "NORMINETTE"
../util/normcheck $repo

../util/printtitle "COMPILE PROJECT"
make -C $repo -s bonus clean
../util/compilecheck $?
if [ $? -ne 0 ]
then
	exit 1
fi

../util/printtitle "COMPILE TESTS"
gcc tests/*.c $repo/libft.a -o output
../util/compilecheck $?
if [ $? -ne 0 ]
then
	exit 1
fi

../util/printtitle "TESTS"
./output

rm -f output
make -C $repo -s fclean