#!/bin/bash

red="\033[0;31m"
green="\033[0;32m"
nocolor="\033[0m"

# Go to script's location
cd $(dirname $0)

if [ $# -ge 1 ]
then
	repo="$1"
else
	repo="repo/"
fi

../util/printtitle "NORMINETTE"
../util/normcheck "$repo/libft/ $repo/*.c $repo/*.h"

../util/printtitle "COMPILE"
make -C repo/ -s all
../util/compilecheck $?
if [ $? -ne 0 ]
then
	make -C repo/ -s fclean
	exit 1
fi

../util/printtitle "TEST"
repo/so_long repo/maps/map.ber

make -C repo/ -s fclean